replicaCount: 1
backoffLimit: 3

image:
  repository: alpine/curl
  tag: 8.9.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations: []

affinity: {}

secret:
  awsKey: grafana-annotator/token
grafanaURL: https://g-614e59cd65.grafana-workspace.us-west-2.amazonaws.com
grafanaAnnotation:
  serviceName:
  env:
  additionalTags: []
ttlSeconds: 60