apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "grafana-annotator.fullname" $ }}-token
  labels:
    app: {{ include "grafana-annotator.name" $ }}
    chart: {{ include "grafana-annotator.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "grafana-annotator.fullname" $ }}-token
  dataFrom:
    - extract:
        key: {{ .Values.secret.awsKey }}